### ISSUE TITLE
Not working on Firefox

### ISSUE THREAD

**Issue by jjc385** [JRJurman/when2meet-people-highlighter#1]
I input the function into the Firefox Dev edition's web console on a when2meet page, which returned:

![image](https://user-images.githubusercontent.com/17333931/32915947-681a6986-cacf-11e7-9f49-caccb7df2706.png)

Then I ran `highlighter("nadia","blue")`, which returned `undefined` :

![image](https://user-images.githubusercontent.com/17333931/32916008-95b147ca-cacf-11e7-96a4-7766df8ef80c.png)

It appears that the code isn't working, though it's entirely possible the mistake is mine.

Please forgive me; I'm entirely new to browser consoles and mostly to javascript, though I do have programming experience.

**Comment by JRJurman** [comment]
By default the function returns nothing (regardless if it works or doesn't)
The names are **case sensitive** so, I'm guessing that perchance it should be `"Nadia"`?

I just tried it on Firefox here and it worked...

**Comment by jjc385** [comment]
How embarrassing -- the case sensitivity was the issue, and it's working beautifully now.  The `undefined` threw me -- I really should have searched what that means in javascript.  My apologies for bothering you with such a triviality.  Thanks for your quick response, and for writing this useful function to begin with.

If I have some time, I'll fork and pull request suggesting a note in about case sensitivity in the readme.  Your choice whether to include it, of course.

**Comment by JRJurman** [comment]
@jjc385 Haha, no problem! It's been a really long while since I did this, so it was nice to return to this and see it still working. Instead of just adding some warnings in the README, I think there are some better solutions:
1) We should just make the check case insensitive.
2) We should throw some kind of error when we can't find a name
3) When we do find a name, let's return something

I don't think it'll be too much work to put those together. I'll probably put those together sometime next week... probably... yeah...
